### PR TITLE
Add installation commands

### LINKED ISSUE #19: Add helpful installation information to README
Right now it's only a pip command to install kadinsky but not a word about clip or opencv. Probably should be something like this:
```
pip install opencv-python
pip install git+https://github.com/openai/CLIP.git
pip install git+https://github.com/ai-forever/Kandinsky-2.git
```

### PR DESCRIPTION
**Pull request by maximxlss**
Closes #19

### CODE REVIEW

**Comment by maximxlss** [comment]
Actually doesn't quite work with this process. Gonna investigate

**Review by Blucknote — COMMENTED** [review]
May be requirements.txt?

**Comment by lachlan-nicholson** [comment]
Why did you remove the clip installation hint?
`pip install git+https://github.com/openai/CLIP.git`

**Comment by maximxlss** [comment]
Sorry, it was my mistake. Fixed

**Pull request closed without merging**
